[BUGFIX AND DEV] Added linting to package json, fixed colors and tab closing
Dpeta/PesterchumOnlineButSilly pull request #12
Opened 2024-02-04 20:36 UTC by laaledesiempre

This are the changes:

- [x] Missing tab closing button (#11 )
- [x] Some colors didn't match (#7 )
- [x] eslint execution was not on package json (#10 )

Now, the thing is, i commented a lot of code on the js file because was not useful since now the button is fixed and use to broke all. but kept it. maybe we can delete it, or not, on future changes.

white colors now depends on the --white variable at `/styles.css`, so, i tested it on my screen but if you or someone finds that a different kind of white is better. now is easy to change, this change is to make it mode comfortable to read on any kind of screens, not eye burning white. also as now depends on a variable a future theme selector would be easier to make

now running eslint is as easy as exec `npm run lint`. this is useful if , in the future, we have multiple things to execute, or we change linter or whatever, it works fine rn. but let me know if somethings not working as intended

2024-02-04 20:41 UTC, laaledesiempre commented
not used variable made eslint scream so now is commented.

2024-02-05 11:09 UTC, laaledesiempre commented
forgor to add the new script on the readme.

2024-02-06 02:31 UTC, Dpeta commented
Closing tabs works good 👍 also easier to press this way on mobile than the previous tiny x. Just leaving the old code commented out for now is probably fine.

Don't think we should replace white with a different color by default though. It's softer on the eyes but the green-ish background makes it look pretty different than what Pesterchum normally looks like, I'd rather leave smthin like that as a theme thing or an option.

![2024-02-06_02-11_1_2](https://github.com/Dpeta/PesterchumOnlineButSilly/assets/69427753/bb4c9ef7-00d0-4250-9d6d-8876dc8763f3) ![2024-02-06_02-11_2](https://github.com/Dpeta/PesterchumOnlineButSilly/assets/69427753/f8d38c86-ce9c-4b3e-9b26-5c83159dfa09)

2024-02-06 13:17 UTC, laaledesiempre commented
Agree, was a mistake, now it "white". it should be this white i dont know why it was like "green". also if you dont like it, is easy to change now, i still have to make all colors responsive to variables for the future theme implementation. see if you like it and tell me.

2024-02-06 14:06 UTC, Dpeta requested changes
![3rg5e0fcpn8c12](https://github.com/Dpeta/PesterchumOnlineButSilly/assets/69427753/17576f0d-3fc9-4662-9a9b-70c07bc0774e)

2024-02-06 14:06 UTC, Dpeta commented on README.md
> +This will run eslint automatic linter and scream about errors, it needs to be flawless for the `CI/CD` building.
```suggestion
This will run ESLint (``eslint --fix``) and automatically fix problems and enforce style guidelines. 
```

2024-02-06 14:26 UTC, laaledesiempre commented
okey changed are now on.

2024-02-06 14:28 UTC, Dpeta commented
woo yeah woo yeah

2024-02-06 14:28 UTC, merged